### ISSUE TITLE
Feat: request check to see if fd exists before downloading

### ISSUE THREAD

**Issue by atomicpages** [pablopunk/fd-find#1]
Interested in adding a check to see if `fd` is already on the user's `$PATH`? Using [`command-exists`](https://npm.im/command-exists) would mean support for *nix and Windows so thre should be no disruption for Windows users. I'd be happy to cook up a PR if there's interest for this

**Comment by pablopunk** [comment]
@atomicpages sure I'll be happy to merge a PR 👍🏻

**Comment by atomicpages** [comment]
@pablopunk PR created #2 🎉
